### ISSUE TITLE
When putting items into Kitchen Cooker game kills itself

### ISSUE THREAD

**Issue by Alatarius** [Andrey2470T/multidecor#7]
I am playing the current version of mintest using minetest_game. Every time I put food items in the stove/oven the game completely stops as if it received the kill command.

this is the error that it gave me:

AsyncErr: Lua: Runtime error from mod '??' in callback detached_inventory_OnPut(): ...es\Minetest\bin\..\mods\multidecor\decor_api/shelves.lua:381: attempt to index local 'self' (a nil value)
stack traceback:
	...es\Minetest\bin\..\mods\multidecor\decor_api/shelves.lua:381: in function <...es\Minetest\bin\..\mods\multidecor\decor_api/shelves.lua:359>

**Comment by Andrey2470T** [comment]
Does this bug exist in the newest (1.2.1) modpack version? And does it happen after first placing and putting food in the cooker? I just think maybe you updated Multidecor from older version to 1.2.0/1.2.1 as there was the massive rewriting of the shelves API including the cooker's one.

**Comment by Alatarius** [comment]
I'm not sure what version it is. It's whatever version is on ContentDB

**Comment by Andrey2470T** [comment]
I've just tested 1.2.0 and 1.2.1 and I can confirm the game doesn't crash when any item is put in the cookers in my case. Could you describe your situation more detailed (on which cirmcumstances, whether you updated to the latest version or not, you placed the cooker in the first time, you rejoined while it is cooking)?

**Comment by Alatarius** [comment]
I did, have something cooking when it crashed. I completely uninstalled the mod then reinstalled and now it seems to be working.

Thank you much for looking into this. It helped with looking at things from a different angle

**Comment by Alatarius** [comment]
It's happening again. I put potato into the kitchen cooker and the game killed itself again with this error:

AsyncErr: Lua: Runtime error from mod '??' in callback detached_inventory_OnPut(): ...es\Minetest\bin\..\mods\multidecor\decor_api/shelves.lua:381: attempt to index local 'self' (a nil value)
stack traceback:
	...es\Minetest\bin\..\mods\multidecor\decor_api/shelves.lua:381: in function <...es\Minetest\bin\..\mods\multidecor\decor_api/shelves.lua:359>

I am using the latest version of mt playing minetest_game with the latest version of your mod downloaded from here on github.

**Comment by Andrey2470T** [comment]
I've found out the reason of this. I got the same error after re-adding cookers in the same positions and then trying to put some food there. That happened because the detached inventories of the previous destructed cookers didn't remove also together with them. I've fixed the issue now.

**Comment by Alatarius** [comment]
Still happening. Same thing happened. I tried potato again and it still killed itself:

AsyncErr: Lua: Runtime error from mod '??' in callback detached_inventory_OnPut(): ...es\Minetest\bin\..\mods\multidecor\decor_api/shelves.lua:381: attempt to index local 'self' (a nil value)
stack traceback:
	...es\Minetest\bin\..\mods\multidecor\decor_api/shelves.lua:381: in function <...es\Minetest\bin\..\mods\multidecor\decor_api/shelves.lua:359>

**Comment by Andrey2470T** [comment]
Does it happen after placing, then destructing and then placing again at the same position the cooker or when exactly? I don't get any crashes in such case.

**Comment by Andrey2470T** [comment]
> Still happening. Same thing happened. I tried potato again and it still killed itself:
> 
> AsyncErr: Lua: Runtime error from mod '??' in callback detached_inventory_OnPut(): ...es\Minetest\bin..\mods\multidecor\decor_api/shelves.lua:381: attempt to index local 'self' (a nil value) stack traceback: ...es\Minetest\bin..\mods\multidecor\decor_api/shelves.lua:381: in function <...es\Minetest\bin..\mods\multidecor\decor_api/shelves.lua:359>
> 
> I used the updated one that you have here on github, problem still not resolved.

Maybe try to place a new cooker and see if there is that crash still. I don't get those crashes from the latest commit in any case.

**Comment by Alatarius** [comment]
I tried that and still get the same issue with the same error previously posted.

I uninstalled the mod, deleted all nodes from it. Then I reinstalled the mod and tried the same thing and still get the error and crash.

⁣Get BlueMail for Android ​

**Comment by Andrey2470T** [comment]
> I tried that and still get the same issue with the same error previously posted. I uninstalled the mod, deleted all nodes from it. Then I reinstalled the mod and tried the same thing and still get the error and crash. ⁣Get BlueMail for Android ​
> […](#)
> On Sep 18, 2023, 11:00 AM, at 11:00 AM, Andrey ***@***.***> wrote: > Still happening. Same thing happened. I tried potato again and it still killed itself: > > AsyncErr: Lua: Runtime error from mod '??' in callback detached_inventory_OnPut(): ...es\Minetest\bin..\mods\multidecor\decor_api/shelves.lua:381: attempt to index local 'self' (a nil value) stack traceback: ...es\Minetest\bin..\mods\multidecor\decor_api/shelves.lua:381: in function <...es\Minetest\bin..\mods\multidecor\decor_api/shelves.lua:359> > > I used the updated one that you have here on github, problem still not resolved. Maybe try to place a new cooker and see if there is that crash still. I don't get those crashes from the latest commit in any case. -- Reply to this email directly or view it on GitHub: [#7 (comment)](https://github.com/Andrey2470T/multidecor/issues/7#issuecomment-1724107353) You are receiving this because you authored the thread. Message ID: ***@***.***>

I can't fix the problem without detailed description of circumstances on which it happens as I already told you earlier. Just saying the game crashes after putting food in the cooker is not sufficient for understanding the whole situation.

**Comment by Andrey2470T** [comment]
> That's exactly what happens. It doesn't get more detailed than that. If I put any food in the cooker the game crashes with the error that I posted previously. ⁣Get BlueMail for Android ​
> […](#)
> On Sep 19, 2023, 3:00 AM, at 3:00 AM, Andrey ***@***.***> wrote: > I tried that and still get the same issue with the same error previously posted. I uninstalled the mod, deleted all nodes from it. Then I reinstalled the mod and tried the same thing and still get the error and crash. ⁣Get BlueMail for Android ​> […](#) > On Sep 18, 2023, 11:00 AM, at 11:00 AM, Andrey ***@***.***> wrote: > Still happening. Same thing happened. I tried potato again and it still killed itself: > > AsyncErr: Lua: Runtime error from mod '??' in callback detached_inventory_OnPut(): ...es\Minetest\bin..\mods\multidecor\decor_api/shelves.lua:381: attempt to index local 'self' (a nil value) stack traceback: ...es\Minetest\bin..\mods\multidecor\decor_api/shelves.lua:381: in function <...es\Minetest\bin..\mods\multidecor\decor_api/shelves.lua:359> > > I used the updated one that you have here on github, problem still not resolved. Maybe try to place a new cooker and see if there is that crash still. I don't get those crashes from the latest commit in any case. -- Reply to this email directly or view it on GitHub: [#7 (comment)]([#7 (comment)](https://github.com/Andrey2470T/multidecor/issues/7#issuecomment-1724107353)) You are receiving this because you authored the thread. Message ID: ***@***.***> I can't fix the problem without detailed description of circumstances on which it happens as I already told you earlier. Just saying the game crashes after putting food in the cooker is not sufficient for understanding the whole situation. -- Reply to this email directly or view it on GitHub: [#7 (comment)](https://github.com/Andrey2470T/multidecor/issues/7#issuecomment-1725195116) You are receiving this because you authored the thread. Message ID: ***@***.***>

I updated the modpack few days ago. Do you still have that problem in the newest release 1.2.2?
